name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Lint
      run: cmake -D FORMAT_COMMAND=clang-format-18 -P cmake/lint.cmake

  vcpkg:
    name: vcpkg (${{matrix.version}}, ${{matrix.config.os}})
    needs: [lint]
    runs-on: ${{matrix.config.os}}
    permissions:
      packages: write
      contents: read
    env:
      VCPKG_COMMIT: 74e6536215718009aae747d86d84b78376bf9e09 # 2025.10.17
      # Note: Change 'ekilmer-packages' to your own username or org
      NUGET_FEED_URL: https://nuget.pkg.github.com/ekilmer-packages/index.json
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN != '' && secrets.PACKAGE_TOKEN || secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-2025,
             name: windows,
             nuget: nuget}
          - {os: macos-15,
             name: macos,
             nuget: mono `vcpkg fetch nuget | tail -n 1`}
          - {os: ubuntu-24.04,
             name: ubuntu,
             nuget: mono `vcpkg fetch nuget | tail -n 1`}
        version:
          - HEAD
        # TODO: Uncomment this when https://github.com/Vector35/binaryninja-api/pull/7538 is merged
        #   - dev
        #   - "5.1.8104-stable"
        #   - "5.0.7648-stable"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: 'true'
        persist-credentials: false

    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@f176ccd3f28bda569c43aae4894f06b2435a3375 # v4.2.3

    - name: Update binaryninja-api submodule
      shell: bash
      run: |
        cd external/binaryninja-api
        if [ "${{matrix.version}}" != "HEAD" ]; then
          git remote set-url origin https://github.com/Vector35/binaryninja-api.git
          git fetch --depth=1 --force origin "refs/heads/Vector35:refs/remotes/origin/${{matrix.version}}"
          git checkout --force "origin/${{matrix.version}}"
        fi
        git show --no-patch HEAD
        git submodule update --init --depth=1 vendor/

    - name: Install static analyzers and dependencies
      if: matrix.config.os == 'ubuntu-24.04'
      run: |
        sudo wget --output-document=/usr/share/keyrings/apt.llvm.org.asc https://apt.llvm.org/llvm-snapshot.gpg.key
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/apt.llvm.org.asc] http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get --yes update

        sudo apt-get install --yes --no-install-recommends cppcheck clang-tidy-22
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-22 900

        cppcheck --version
        clang-tidy --version

        sudo apt-get install --yes mono-complete

    - name: Setup vcpkg environment
      shell: bash
      run: |
        git -C "$VCPKG_INSTALLATION_ROOT" fetch --all
        git -C "$VCPKG_INSTALLATION_ROOT" reset --hard ${{ env.VCPKG_COMMIT }}
        "$VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.sh"

        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"

        if [[ "${{ matrix.config.name }}" == "macos" ]]; then
          brew install mono
        fi

        ${{ matrix.config.nuget }} \
          sources add \
          -Source "${{ env.NUGET_FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ github.repository_owner }}" \
          -Password "${{ env.PACKAGE_TOKEN }}"
        ${{ matrix.config.nuget }} \
          setapikey "${{ env.PACKAGE_TOKEN }}" \
          -Source "${{ env.NUGET_FEED_URL }}"

    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

    - name: Configure CMake
      env:
        VCPKG_BINARY_SOURCES: clear;nuget,${{ env.NUGET_FEED_URL }},readwrite
      run: cmake --log-level=DEBUG
            --preset ci-${{matrix.config.name}}
            -DBN_USER_PLUGINS_DIR="${{ github.workspace }}/install-plugin"

    - name: Build
      run: cmake --build build --config Release -j 4

    - name: Install
      run: cmake --build build --config Release --target install

    - name: Upload artifact
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{matrix.config.name}}-${{matrix.version}}
        path: install-plugin/
